### ISSUE TITLE
Skillbridge Function interface is not expressive enough for SKILL

### ISSUE THREAD

**Issue by nielsbuwen** [unihd-cag/skillbridge#106]
Some SKILL functions can take `@key` arguments in a list:

```lisp
someFunction(1 2 3 list( ?x 10 ?y 20 ) )
```

Currently, this is not representable in python.

I suggest two things:

- A `Key(name: str)`  named tuple that is converted to the SKILL code `?{name}`
- A `keys(**keys: Any)` function that is converted to a list of key value pairs:

```python
Key('x')  # -> ?x
Key('xyz')  # -> ?xyz
keys(x=1, xyz=123)  # -> list(?x 1 ?xyz 123)
```

We can then call the function above like this:

```python
ws.prefix.some_function(1, 2, 3, [Key('x'), 10, Key('y'), 20])
ws.prefix.some_function(1, 2, 3, keys(x=10, y=20))
```

The standalone `Key` could become necessary later, because `?xyz` is actually a valid SKILL symbol. They are, however, different from the "normal" `Symbol`s.

```lisp
?x == 'x  ;; -> nil
```

**Comment by TM90** [comment]
It seems to be necessary. The proposal sounds good.

We should document this really good otherwise this will become quite ambiguous.
