### ISSUE TITLE
Conda Package

### ISSUE THREAD

**Issue by curtisma** [unihd-cag/skillbridge#149]
I use Conda as a package manager instead of pip. If I submit a PR request for a conda recipe would you be interested in uploading skillbridge to conda-forge?  Or would you mind if I uploaded it?

**Comment by nielsbuwen** [comment]
Hi,

we will take a look at conda-forge. Thank you for the suggestion?

Out of curiosity? What prevents you from installing the `skillbridge` via `pip` in your conda environment?

**Comment by nielsbuwen** [comment]
Thank you for the work. I don't believe that i have the capacity (or the experience) at the moment to be a maintainer for the conda recipe. I would be very happy if you could do that.

**Comment by curtisma** [comment]
Ok, sounds good.

**Comment by curtisma** [comment]
This has been added to [Conda-Forge](https://conda-forge.org/).  
The feedstock can be found at:
https://github.com/conda-forge/skillbridge-feedstock
