### ISSUE TITLE
calling funobj without 'funcall'

### ISSUE THREAD

**Issue by psuhan** [unihd-cag/skillbridge#151]
Hi, I found that sometimes a RemoteObject can be 'funobj' type.
For example, you get a 'axlrdb' type object when you request a simulation result data base using 'axlReadDataDB' function.
The 'axlrdb' object has 'funobj' type members, which cannot be directly evaluated in python side with ().
Instead, it should be indirectly called using skill function, 'funcall'.
```
rdb = client.axl.read_res_d_b(history_rdb_path)

rdb
#<remote axlrdb@0x1d9b8140>

dir(rdb)
#['close', 'corner', 'corners', 'debug', 'finalize', 'help', 'invalidate', 'output', 'outputs', 'param', 'params', 'point', 'points', 'test', 'tests']

rdb.params
#<remote funobj@0x1c2fb0c0>

rdb.params() # does not work
#Traceback (most recent call last):
#  File "test_axl.py", line 20, in <module>
#    print(rdb.params())
#TypeError: 'RemoteObject' object is not callable

ws['funcall'](rdb.params) # indirect call
#[<remote axlrdbp@0x1fb69d10>, <remote axlrdbp@0x1fb6a080>, <remote axlrdbp@0x1fb6a098>]
```
It looks good to use () to evaluate 'funobj'.
I think putting ws['funcall'] part into `__call__` method inside RemoteObject class can be a solution. Below is my quick solution.
```
    def __call__(self, *args, **kwargs):
        typ = self.skill_type or self.skill_parent_type
        if typ == 'funobj':
            args = tuple([self] + list(args))
            command = self._translate.encode_call('funcall', *args, **kwargs)
            result = self._channel.send(command)
            return self._translate.decode(result)
```
Thanks!!

Pyungsu

**Comment by nielsbuwen** [comment]
Hi,

this sounds like a reasonable addition. We will implement it.

Thank you for reporting this.
