### ISSUE TITLE
Digit(number) characters in member/attributes are missing in python side

### ISSUE THREAD

**Issue by psuhan** [unihd-cag/skillbridge#152]
When called in python side, digit characters in attribute/member names are disappeared.
layer1 -> layer
layer2 -> layer
Referring to the attr/member with the proper name (with digit characters) still works.

python side,
```python
tfid = client.tech.get_tech_file(client.dd.get_obj("mytech"))
dir(tfid.via_defs[0])
# ['group_members', 'implant', 'implant', 'layer', 'layer', 'layer_num', 'layer_num', 'name', 'obj_type', 'params', 'prop', 'resistance_per_cut', 'tech', 'tech_file', 'well_or_substrate']
tfid.via_defs[0].layer1 # works!!
```
skill side,
```lisp
car(tfid->viaDefs)->?
(objType prop groupMembers tech techFile
    name layer1 layer1Num layer2 layer2Num
    resistancePerCut implant1 implant2 wellOrSubstrate params
)
```
Thanks!

Pyungsu

**Comment by nielsbuwen** [comment]
Hi,

thank you for finding this.

This is definitely a bug. Probably when we convert the SKILL camelCase to Python snake_case.

I will look into it.
