### ISSUE TITLE
Subtracting waveforms

### ISSUE THREAD

**Issue by bou4** [unihd-cag/skillbridge#169]
Hi all,

I am busy porting part of Ocean to Python to better document the sizing of my circuits in a Jupyter environment.
However, I cannot seem to find a way to subtract two waveforms (in the Ocean environment, I only want to download the waveform data when plotting, but not for general arithmetic operations).
I would like to do something like this:
```python
class Waveform:
  def __sub__(self, other):
     ...
vop = Waveform(ws['getData']('/vop'))
von = Waveform(ws['getData']('/vop'))

vod = vop - von
```
I found out that you can access the variable using the `_variable` property, but how would one execute an infix operation and create a new RemoteObject representing the result?
Can you guide me in the right direction?

Kind regards,

Caro

**Comment by bou4** [comment]
I must have complicated things too much:
```python
class Waveform:
    def __init__(self, waveform) -> None:
        self.waveform = waveform

    def __sub__(self, other: Waveform) -> Waveform:
        return Waveform(ws['plus'](self.waveform, ws['minus'](other.waveform)))

    def pull(self) -> tuple[list[float], list[float]]:
        """Pull the waveform for further processing in the local environment.

        Args:
            waveform: The waveform to pull.

        Returns:
            Tuple containing the x and y values of the waveform.
        """
        x, y = ws['abWaveToList'](self.waveform, transpose=True)

        return x, y
```
Is this the way to go?

**Comment by nielsbuwen** [comment]
Hi,

can you share the skill code you are working on? I'm not familiar with these waveforms.

**Comment by bou4** [comment]
Hi

I am working on this class `Waveform` which encapsulates a `srrWave` object, as received by Ocean functions like `getData`.
I got it working like this: https://github.com/bou4/ocean/blob/7e045b580bc52601191294f0fc2b1e2423982525/src/ocean/ocean.py#L22, so in fact I do not have a problem anymore.
But I am interested in knowing if this is how you would do it or are there better ways you see fit?

KInd regards

Caro Meysmans

**Comment by nielsbuwen** [comment]
Wrapping the Waveforms and implementing the operators on top of that seems like the best option to me.

We could even discuss if we want to add that to this library.

**Comment by TM90** [comment]
If each of the operator dunder methods map to a single skill operator it would be fine to add this functionality to the skillbridge.

The operator in question at the moment would be `__sub__` which uses an addition with a minus. 

@bou4 Is it possible to only use minus, i.e. can you write `(minus leftWaveform rightWaveform)` 
instead of `(plus leftWaveform (minus rightWaveform))`?

Best regards

Tobias

**Comment by bou4** [comment]
As far as I know, `(minus leftWaveform rightWaveform)` is not possible.

Kind regards

Caro Meysmans

**Comment by nielsbuwen** [comment]
That's unfortunate. Then it does not make sense to implement these operators directly in the skillbridge.

I will close the issue. Feel free to reopen it when there is new information
