### ISSUE TITLE
Option to Set Log Files' Location

### ISSUE THREAD

**Issue by curtisma** [unihd-cag/skillbridge#183]
I'd like to add a way to relocate the log files since a lot of times my users don't have permission to save to the install location of them.

We propose overwriting the default location when an environment variable, "**SKILLBRIDGE_LOG_DIRECTORY_PATH**" is set to the directory path where the logs will be saved.  Then all 3 log files will be saved in that directory with the following names:

- SKILL-side IPC server log: **skillbridge_skill_ipc_server.log**
- Python-side server log: **skillbridge_python_server.log**
- Python client log: **skillbridge_python_client.log**

I'll create a PR.  Just let me know if anyone has any feedback on the approach or the proposed log names

Should we consider putting the logs by default in the user's directory?  
If so, should the log names contain the workspace id so there are seperate logs for each workspace ID?

**Comment by curtisma** [comment]
I started draft PR #184

**Comment by curtisma** [comment]
It seems there is no logging in the client code.  Was that a design decision?

**Comment by nielsbuwen** [comment]
Hi,

we heavy use virtual environment so we don't have that permission problem at all. But you are not the first to request such a feature. The overall idea to set an environment variable that controls the directory of all our log files seems like a good idea.

I would say that the default should be the old behaviour i.e. the current working directory. To distinguish between the different workspace ids i suggest to include the workspace id in each log message. Then we can have one file for all the workspaces.

My suggestion for the names is:

- `SKILLBRIDGE_LOG_DIRECTORY`
- `skillbridge_skill.log`
- `skillbridge_server.log`
- `skillbridge_client.log`

> It seems there is no logging in the client code. Was that a design decision?

We just didn't see the need to log anything there. Are there events in particular you want to log?

If i remember correctly we had a log file that tracked all the interaction with skill. So everything that was sent from python to skill and the other way round produced a log entry. That slowed things down a lot, especially when the messages were large.

But other things could be logged of course.

One more note: @TM90 is on vacation right know and i don't want to decide on these things alone.

**Comment by curtisma** [comment]
Ok, sounds good.  I updated the names in the draft PR to match your proposal.

> Are there events in particular you want to log?

No, not really.  I think that can be handled by the client application code.

**Comment by curtisma** [comment]
When will @TM90 be back to review the proposed updates?

@nielsbuwen

**Comment by nielsbuwen** [comment]
Hi, we talked offline. I will do a full review on Monday (maybe Sunday).

Things i already noticed:

- what is the `skillbridge.init.il` file. That does not seem to be part of the logging changes
- one of the log files in the SKILL file ignores the directory variable

If i remember correctly the SKILL IPC creates two log files. I will investigate that.

**Comment by TM90** [comment]
@curtisma 

I [reviewed ](https://github.com/unihd-cag/skillbridge/pull/184#pullrequestreview-1019331803) the proposed changes and also let @nielsbuwen know.

We use several tools to lint and check the code my impression was that every PR should trigger a Github action running: 

- black 
- flake8
- mypy
- isort

Is there something broken @nielsbuwen or did we never set it up that way.

**Comment by TM90** [comment]
The above PR #185 is an alternative proposed PR by us, which runs through the CI. 

@curtisma does this PR solve this issue from your perspective.

**Comment by TM90** [comment]
PR is merged and released with [1.2.17](https://github.com/unihd-cag/skillbridge/releases/tag/releases%2F1.2.17)
