### ISSUE TITLE
Add Documentation Link to GitHub "About"

### ISSUE THREAD

**Issue by curtisma** [unihd-cag/skillbridge#186]
It would be nice to have a link to your documentation in the about section of the GitHub repo page so it shows up similar to this:

![image](https://user-images.githubusercontent.com/4685385/176721897-36aa6269-f3f4-404f-a95c-1badd1e5aee1.png)

You can just select the gear icon next to the about section to update the URL in the website field:

![image](https://user-images.githubusercontent.com/4685385/176721243-2488fd2c-30bb-49a9-8d94-a68990157768.png)

**Comment by TM90** [comment]
Good idea, I added the doc link.
