### ISSUE TITLE
How to Identify a Global Variable in Skill

### ISSUE THREAD

**Issue by Bobobozz** [unihd-cag/skillbridge#199]
cdfgData is  a global variable in skill, and I want to change the value of cdfgData using python. How can I call the Global Variable in Skill by using python?
I have tried that use the variable names directly in Python,but it seems doesn't work.
skill code:
`cdfgData = cdfGetInstCDF(inst)`
python code:
`cdfgData = ws.cdf.get_Inst_CDF(inst)`

**Comment by nielsbuwen** [comment]
Hi,

if you really need global variables, you can use a skill function to set them:

```python
from skillbridge import Workspace, Symbol

ws = Workspace.open()

cdfg_data = ws.cdf.get_inst_CDF.var(...)
ws['set'](Symbol('cdfgData'), cdfg_data)
```

When you don't need the variable in python, it is possible to eliminate one round-trip:

```python
ws['set'](Symbol('cdfgData'), ws.cdf.get_inst_CDF.var(...))  # notice the .var
```

**Comment by Bobobozz** [comment]
Hi nielsbuwen,
Thank you for your reply! It works well!
