### ISSUE TITLE
debug long list performance problems

### ISSUE THREAD

**Issue by DMKun** [unihd-cag/skillbridge#204]
when debug a local RemoteObject list(lenth more then1000). I't take long time to get typ.
if remove typ，print RemoteObject very fast.
``` python
a = ws.axl.get_sel_set()
# print very slow
print(a)
```
``` python
class RemoteObject(RemoteVariable):
    def __str__(self) -> str:
        typ = self.skill_type or self.skill_parent_type
        if typ == 'open_file':
            name = self._call('lsprintf', '%s', self)[6:-1]  # type: ignore
            return f"<remote open_file {name!r}>"
        return f"<remote {typ}@{hex(self.skill_id)}>"
```

**Comment by nielsbuwen** [comment]
Hi,

yes, unfortunately when printing a list, the type is checked for each element individually.

What we could do is, implement `__repr__` without querying the type.

We will discuss that.
