### ISSUE TITLE
[SUPPORT] Using the plot function with OCEAN scripting in Python 

### ISSUE THREAD

**Issue by PaulKokhanov1** [unihd-cag/skillbridge#221]
Hello, 
I was having issues on how to use the plot function in OCEAN using skillbridge. I am using the code line 
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/9b2f8d44-75ee-4885-9680-d0643dfc6891)
However I get the following error when running my code
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/477d2fdc-61c0-4b40-8719-4fd5f962121f)
What would be the best way to solve this issue, as trying to do something along the lines of ws['plot']("VS('/net1')") causes python to think I am attempting to plot the expression "VS('/net1')" instead of just net1, and thus virtuoso is unable to find the expression in my dc results. Any suggestions? Thanks

**Comment by nielsbuwen** [comment]
Hi,

can you show me the original OCEAN code that you want to translate?

Is it `plot("VS('/net')")` or `plot(VS('/net'))`.

The first code would be `ws['plot']("VS('/net')")` in python and the second is a bit more complicated:

```
ws['plot'](ws['VS']('/net'))  # this should work
```

**Comment by PaulKokhanov1** [comment]
Hello,

Yes it was the second one, specifically,
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/fdde286d-4040-4acb-aee8-b202a42a4cdd)

But `ws['plot'](ws['VS']('/net'))` did work! Thank you so much.

**Comment by nielsbuwen** [comment]
Glad i could help.

Depending on the size of the return value of `VS("/net")` it could be faster to only compute that part on the SKILL side.

```python
ws['plot'](ws['VS'].var("/net"))  # notice the 'var'
```

`ws['VS'].var` is a symbolic expression that is only evaluated on the SKILL side. My original answer sends the results from `VS` to python and then back to SKILL. With the new snippet you save that round-trip. The downside is that you can't use the result from `VS` on the python side.

Feel free to close the issue, when you don't have any more questions about this.
