### ISSUE TITLE
[SUPPORT] Unsure how to convert the following code to Python

### ISSUE THREAD

**Issue by PaulKokhanov1** [unihd-cag/skillbridge#224]
Hello, sorry for the simple question but how would you convert the following code to python? 
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/dc4ffd13-04cc-471d-9b20-4555865c70c5)

Specifically the `'` occurring before the corner details, I tried the following,

![image](https://github.com/unihd-cag/skillbridge/assets/69466838/eeaefe08-df79-4843-bb6c-475551f671b6)

But it does not seem to be correct. Any ideas? Thanks!

**Comment by TM90** [comment]
Hey,

I can only try the command without context but this should work:

``` python
from skillbridge import Workspace

ws = Workspace.open()
ws.ocnxl.corner("Nom_top", [
     ["variable", "temperature", "40"],
     ["variable", "vdd", "1.1"],
     ["model", "/test/path/to/test.scs", "\"top_tt\""]
])
```

1. Since ocnxl is a subsystem we can access it without the `ws[]` mechanism via prefix
2. It seems that `ocnxlCorner` accepts a list of a list

If this does not work providing a minimal example would help.

**Comment by TM90** [comment]
If this did not solve you issue feel free to reopen this one.
