### ISSUE TITLE
[SUPPORT] Starting pyServer without opening Virutoso

### ISSUE THREAD

**Issue by PaulKokhanov1** [unihd-cag/skillbridge#228]
Hello, this is more of a question on the capabilities of skillbridge rather than an issue. I have a task where I use skill code to extract a list of pins, specifically, 
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/45a36760-d53d-428a-8af3-e5d8e8dc4cc7)

I was using skillbridge to launch this procedure during my python script and analyze it using python. However, I was wondering what are my options to launch this piece of code without starting virtuoso? Is it even possible? I am a little doubtful since I would specify the library name, cell name and view name in the procedure call and I imagine it needs virtuoso to be open in order to process it. But maybe there is a way to "start" virtuoso without enabling the GUI? Any ideas/advice or even directions on where to look? Thanks. Feel free to further ask me questions if I was not clear enough with my goal.

**Comment by TM90** [comment]
Virtuoso is needed since the methods are translated and executed in the skill interpreter

There is a nograph mode for virtuoso so it can be started without a gui:

But then you still have to start the skillbridge server.

You can echo the command into virtuoso:

``` bash
echo "pyStartServer" | virtuoso -nograph &> /dev/null &
python your_client_script.py
```

In your client script you have to wait until the skillbridge server is started. Otherwise you wont get the Workspace to open.

I hope this helps.

**Comment by PaulKokhanov1** [comment]
Thanks for the prompt reply! Do I first have to load the python_server.il prior to invoking the pyStartServer? If so, what would be the code to do this via the terminal?

**Comment by TM90** [comment]
Yes! I would put the python_server.il into a corresponding cds init or similar which is auto loaded on startup.

**Comment by PaulKokhanov1** [comment]
Sorry but I am very unfamiliar with using the terminal, I realize the init will be auto loaded however, I am not sure how to define and create it, and specifically what "startup" you mean? do you mean when the nograph version of virtuoso is started? Thanks again for all the help!

**Comment by TM90** [comment]
There are config files which are loaded on virtuoso startup.

Virtuoso will look at startup for a .cdsinit file in your current working path or home path and load it.

**Comment by nielsbuwen** [comment]
Maybe we should document this?

**Comment by TM90** [comment]
> Maybe we should document this?

You mean that the `load(python_server.il)` could reside in the .cdsinit?

**Comment by nielsbuwen** [comment]
The whole process of starting virtuoso without a gui and connecting skillbridge.

**Comment by PaulKokhanov1** [comment]
I see, unfortunately within my company I don't have access to editing the .cdsinit file, what other options do I have?

**Comment by PaulKokhanov1** [comment]
is it as simple as just calling it .cdsinit ? how do I specify that it should correlate to the virtuoso startup and not some other application?

**Comment by TM90** [comment]
It is just a file called `.cdsinit` the load order and that virtuoso looks for that specific file is virtuoso specific behaviour. Other applications should not look for it.

**Comment by PaulKokhanov1** [comment]
I understand, so other applications would have an init file but most likely with a different name, ok, thanks again for the help, I will see what I can do and ask anymore questions if I have any.

**Comment by PaulKokhanov1** [comment]
Actually, one quick question, what does this part in the command line code do `&> /dev/null &` ?

**Comment by TM90** [comment]
`&>` - redirects stdout and stderr of the application in this case to `/dev/null` so it dismisses it.
the `&` afterwards runs the command in background so it does not block your session.

**Comment by PaulKokhanov1** [comment]
I get the following error trying to run that command 
![image](https://github.com/unihd-cag/skillbridge/assets/69466838/fa5d0247-8e5b-4c43-8a31-7916f008012d)

**Comment by TM90** [comment]
> I get the following error trying to run that command ![image](https://user-images.githubusercontent.com/69466838/256585624-83f84fef-c487-4adf-bc06-23de12bb31cc.png)

The same command runs sucessfully virtuoso in the background on my side

**Comment by nielsbuwen** [comment]
@PaulKokhanov1 what kind of Shell are you using? `virtuoso -nograph &> /dev/null &` is a valid bash command
