### ISSUE TITLE
[SUPPORT]autogeneration via stub file (workspace.pyi) in vsCode

### ISSUE THREAD

**Issue by PiyushSaini07** [unihd-cag/skillbridge#229]
Hi,

I followed the[ doc](https://unihd-cag.github.io/skillbridge/usage/quickstart.html#optional-one-time-setup) for autocompletion feature for SKILL functions. I'm using vscode for coding.

As soon as I did that I lost autocompletion even for Workspace import in 
`from skillbridge import Workspace`. 
![image](https://github.com/unihd-cag/skillbridge/assets/113677030/adc9f5d8-9c44-4e97-a640-afd83afe4446)

Also, I'm not getting any autocomplete prompt for the SKILL functions.

Is the autocomplete feature available only for pyCharm? 

P.S.: Running `skillbridge generate` generated a file workspace.pyi in the client directory. Content:
![image](https://github.com/unihd-cag/skillbridge/assets/113677030/6a24bcdd-cfc6-4367-ba52-820fb839765e)
I'm using python 3.6.8.

**Comment by nielsbuwen** [comment]
Hi,

this is a bug. Looks like the behaviour of stubgen changed. We will fix it.

**Comment by TM90** [comment]
The bugfix is now released with [1.5.1](https://github.com/unihd-cag/skillbridge/releases/tag/releases%2F1.5.1)

``` bash
pip install --upgrade skillbridge
```

will update to the latest version.

**Comment by PiyushSaini07** [comment]
After updating, its working.
Thanks!

Closing the issue.
