### ISSUE TITLE
[FEATURE] enter feature summary here

### ISSUE THREAD

**Issue by ClarenceChee** [unihd-cag/skillbridge#245]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when:
using func:  ws.hdl.generate_text_database

**Describe the solution you'd like**

add a line after line number 115:
" hdl: FunctionCollection"

**Comment by ClarenceChee** [comment]
add a line after line number 115:
" hdl: FunctionCollection"
=====>
add a line after line number 115 in skillbridge/client/workspace.py:
" hdl: FunctionCollection"

**Comment by TM90** [comment]
Both prefixes should be available in the 1.7.0 release!
