### ISSUE TITLE
[SUPPORT] An example to place layout cells next to each other

### ISSUE THREAD

**Issue by avlsi** [unihd-cag/skillbridge#247]
I'm looking for example code that employs skillbridge to design a schematic layout, with a focus on arranging cells side by side. I have a collection of cells that must be positioned adjacent to each other. I need the code to retrieve the width and height from the pcell and use this information to construct the layout. Any help or suggestions on this matter would be highly valued.

**Comment by TM90** [comment]
This seems to be more a general skill question/problem.

We have minimal example with layout instances where the bounding box of instances are read from the layout.

This example can be found [here](https://unihd-cag.github.io/skillbridge/examples/inst-statistics.html)

To see how to move, rotate or create instances take a look at `Virtuoso Studio Design Environment SKILL Reference` and `Virtuoso Relative Object Design SKILL Reference` which can be found at the cadence support page.

Methods to look up in the documents are i.e. `dbMoveFig(...)` which would translate for skillbridge to `ws.db.move_fig(...)`
