### ISSUE TITLE
How to use underlying api

### ISSUE THREAD

**Issue by xiaohangguo** [unihd-cag/skillbridge#252]
I'd like to ask how to call the underlying api like` SymbolToString` in python.

**Comment by nielsbuwen** [comment]
In Python a `Symbol` is just a named tuple and you can extract the string value like this:

```python
my_symbol = some_function_that_returns_symbol(...)

print(my_symbol.name)
```

To call arbitrary functions you can also use the `Workspace` like this:

```python
symbol_name = ws['symbolToString'](my_symbol)
```

**Comment by xiaohangguo** [comment]
Thanks！！！！I didn't know you could just use that. @nielsbuwen 
`ws['xxxx'](arg)`

Thank you very much, I found a feature where I can write custom il files in skill, implement special functions and then access them that way.
wow!

I'm working on rewriting il files to python interfaces and this feature will help me reduce the amount of code, great!
