### ISSUE TITLE
Why did I encounter the "RuntimeError: The server unexpectedly died" error?

### ISSUE THREAD

**Issue by zephyruswqs** [unihd-cag/skillbridge#257]
I am testing using outputting() to receive strings output by virtuoso. According to the example in virtuoso's function documentation, I need to use close() to close the port of oustring() after using getOutstring().

The problem now is that after testing in Python, it was found that using close() to close oustring() would result in a "RuntimeError: The server unexpectedly died" error. May I ask if there is a problem with my operation?

* Example of document:
![image](https://github.com/unihd-cag/skillbridge/assets/83122078/ddcd418c-9d2e-43ad-8e7b-1b8aab591be5)

*My code:
![image](https://github.com/unihd-cag/skillbridge/assets/83122078/a74e63be-7d05-4acc-b2f6-10dce8eb808a)

*Error message:
![image](https://github.com/unihd-cag/skillbridge/assets/83122078/c01b538d-13a9-47fa-ba6c-d6b392c156a8)

**Comment by nielsbuwen** [comment]
This seems to be indeed a bug on our side. I'm investigating the issue

**Comment by nielsbuwen** [comment]
The command for the `close(...)` function call was mistaken for an internal `close` command which shuts down the connection of the Workspace with the server. The linked PR fixes this.

When it is merged, we will deploy a release

**Comment by TM90** [comment]
Fixed in skillbridge [1.7.1 release](https://github.com/unihd-cag/skillbridge/releases/tag/releases%2F1.7.1)

To update use `pip install --upgrade skillbridge`

**Comment by nielsbuwen** [comment]
The release has been deployed as version `1.7.1`

**Comment by zephyruswqs** [comment]
> The command for the `close(...)` function call was mistaken for an internal `close` command which shuts down the connection of the Workspace with the server. The linked PR fixes this.
> 
> When it is merged, we will deploy a release

Okay, thank you. It's working normally now.
