### ISSUE TITLE
[SUPPORT] running skillbridge without virtuoso GUI

### ISSUE THREAD

**Issue by kakbydima** [unihd-cag/skillbridge#264]
Hello there, 
I wanted to ask how I could run the skillbridge without opening virtuoso GUI.
I know that for skill code to run like that one can just type: virtuoso -nograph -replay <skillcode.il>
Wondering if the skillbridge has such functionality

**Comment by nielsbuwen** [comment]
With `virtuoso -nograph`  virtuoso opens without a GUI. There you get the same CIW as you would with the GUI mode.

Just type in the `load(...)` and `pyStartServer` commands and you are good to go.

**Comment by TM90** [comment]
I hope this answered your questions. If not feel free to reopen the issue.

**Comment by kakbydima** [comment]
Great, this is what I needed. Thank you!
