### ISSUE TITLE
CLI script for ease of use

### ISSUE THREAD

**Issue by nielsbuwen** [unihd-cag/skillbridge#81]
Maybe we need a CLI script as a replacement to the `__main__.py` script for users that are not familiar with Python.

E.g.

```bash
skillbridge
# should print the path to the server
# should print if the functions have been dumped
# should print if the static completion stubs have been generated

skillbridge generate
# should generate the static completion stubs
```

Other commands could include

- finding all running python server (and killing them)

**Comment by TM90** [comment]
It sounds like a good enhancement if the binary is automatically set up by pip
